prepend-rules: # Clash由上而下遍历规则，推荐将自定义规则排到rule组内靠前位置

  # 格式： - 规则类型,分流目标,应该被分到的节点/节点组
  # 规则类型可参考 https://docs.cfw.lbyczf.com/contents/ui/profiles/rules.html 作者：冇戳懂 https://www.bilibili.com/read/cv18245065 出处：bilibili
  # 参考 https://www.bilibili.com/read/cv18245065

  # 直连
  - DOMAIN,time.is,DIRECT

  # 代理
  - DOMAIN-SUFFIX,jsfiddle.net,Proxy
  - DOMAIN-SUFFIX,origin.com,Proxy
